//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NKS.Customers.Infrastructure.Queries {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Customers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Customers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NKS.Customers.Infrastructure.Queries.Customers", typeof(Customers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Customers SET Forename=@Forename, Initials=@Initials, Surname=@Surname  WHERE Id = @Id.
        /// </summary>
        internal static string ChangeName {
            get {
                return ResourceManager.GetString("ChangeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO dbo.Customers (Id,Title,Forename,Initials,Surname,Email,HashedEmail,MobileNumber,DateofBirth,Status) VALUES
        ///           (@Id,@Title,@Forename,@Initials,@Surname,@Email,@HashedEmail,@MobileNumber,@DateofBirth,@Status).
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM Customers WHERE Id=@Id.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Id,Title,Forename,Initials,Surname,Email,MobileNumber,DateofBirth 
        ///FROM dbo.Customers.
        /// </summary>
        internal static string GetAll {
            get {
                return ResourceManager.GetString("GetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Id,Title,Forename,Initials,Surname,Email,MobileNumber,DateofBirth 
        ///FROM dbo.Customers 
        ///where Status=@status.
        /// </summary>
        internal static string GetAllByStatus {
            get {
                return ResourceManager.GetString("GetAllByStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Id,Title,Forename,Initials,Surname,Email,MobileNumber,DateofBirth 
        ///FROM dbo.Customers 
        ///where Id=@Id.
        /// </summary>
        internal static string GetById {
            get {
                return ResourceManager.GetString("GetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Customers SET Forename=&apos;&apos;, Initials=&apos;&apos;, Surname=&apos;&apos;, Email=&apos;&apos;,MobileNumber=&apos;&apos;, DateofBirth=null, Status = -1 WHERE Id = @Id.
        /// </summary>
        internal static string MarkAsNull {
            get {
                return ResourceManager.GetString("MarkAsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Customers SET Status = @Status WHERE Id = @Id.
        /// </summary>
        internal static string SetStatus {
            get {
                return ResourceManager.GetString("SetStatus", resourceCulture);
            }
        }
    }
}
